//
// automatically generated by spin2cpp v1.05 on Sat Apr 12 16:11:58 2014
// ./spin2cpp screen.spin 
//

#ifndef screenSpin_Class_Defined__
#define screenSpin_Class_Defined__

#include "Simple_Serial.h"
//#include <stdint.h>



class screenSpin {
public:
  static const int _Clkmode = 1032;
  static const int _Xinfreq = 5000000;
  //static const int Gpsdatacache = 195312;
 // Simple_Numbers	Sn;
//  STRINGS2	Str;
  int32_t	Init(void);
  void  Close();
  int32_t	Showvideo(void);
  int32_t	Mediainit(void);
  int32_t	Print(char* Data);
  int32_t	Fadeout(void);
  int32_t	Fadein(void);
  int32_t	Off(void);
  int32_t	On(void);
  int32_t	Contrast(int32_t Num);
  int32_t	Clear(void);
  int32_t	Fontsize(int32_t Size);
  int32_t	Position(int32_t Line, int32_t Col);
  int32_t	Txtcolor(int32_t Hexpart1, int32_t Hexpart2);
  int32_t	Showframe(int32_t Framenum);
  int32_t	Txttrans(int32_t Bool);
  int32_t	Displayimage(void);
  int32_t	Drawrec(int32_t X1, int32_t Y1, int32_t X2, int32_t Y2, int32_t Colorhex1, int32_t Colorhex2);
  int32_t	Changecolor(int32_t Oldcolor1, int32_t Oldcolor2, int32_t Newcolor1, int32_t Newcolor2);
  int32_t	Setbyteaddr(int32_t High1, int32_t High2, int32_t Low1, int32_t Low2);
  int32_t	Setsectoraddr(int32_t High1, int32_t High2, int32_t Low1, int32_t Low2);
  int32_t	Txtbackcolor(int32_t Hex1, int32_t Hex2);
  int32_t	Drawtri(int32_t X1, int32_t Y1, int32_t X2, int32_t Y2, int32_t X3, int32_t Y3, int32_t Color1, int32_t Color2);
  int32_t	SetsectorScores(void);
  int32_t	Setsectorgpsmap(void);
  int32_t	Setsectorcal0(void);
  int32_t	Setsectorcal1(void);
  int32_t	Setsectorcal2(void);
  int32_t	Setsectorcal3(void);
  int32_t	Setsectorcal4(void);
  int32_t	Savestr(char* Data);
  int32_t	Flush(void);
  char*	Readbyteasstring(void);
  int	Readbyte(void);
  int32_t	Writebyte(int32_t Char);
  int32_t   PrintInt(int Data);
private:
  int32_t	Waitforcomplete(void);
    Simple_Serial serial;
};

#endif
