//
// automatically generated by spin2cpp v1.05 on Sat May 10 13:28:09 2014
// ./spin2cpp Simple_Serial.spin 
//

#ifndef Simple_Serial_Class_Defined__
#define Simple_Serial_Class_Defined__

#include <stdint.h>


class Simple_Serial {
public:
  int32_t	Init(int32_t Rxpin, int32_t Txpin, int32_t Baud);
  int32_t	Finalize(void);
  int32_t	Rx(void);
  int32_t	Tx(int32_t Txbyte);
  int32_t	Str(int32_t Straddr);
private:
  int32_t	Sin, Sout, Inverted, Bittime, Rxokay, Txokay;
};

#endif
