//
// automatically generated by spin2cpp v1.05 on Sun Aug  3 17:30:34 2014
// ./spin2cpp ../goonie/Simple_Numbers.spin 
//

#ifndef Simple_Numbers_Class_Defined__
#define Simple_Numbers_Class_Defined__

#include <stdint.h>

class Simple_Numbers {
public:
  static const int Max_len = 64;
  int32_t	Dec(int32_t Value);
  int32_t	Decf(int32_t Value, int32_t Width);
  int32_t	Decx(int32_t Value, int32_t Digits);
  int32_t	Hex(int32_t Value, int32_t Digits);
  int32_t	Ihex(int32_t Value, int32_t Digits);
  int32_t	Bin(int32_t Value, int32_t Digits);
  int32_t	Ibin(int32_t Value, int32_t Digits);
private:
  int32_t	Idx;
  uint8_t	Nstr[64];
  int32_t	Clrstr(int32_t Straddr, int32_t Size);
  int32_t	Decstr(int32_t Value);
  int32_t	Hexstr(int32_t Value, int32_t Digits);
  int32_t	Binstr(int32_t Value, int32_t Digits);
};

#endif
